"""Add comment column to Book table

Revision ID: ff8a0d342773
Revises: 3dc4f5285b3b
Create Date: 2024-06-22 14:24:56.613988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8a0d342773'
down_revision: Union[str, None] = '3dc4f5285b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'comment')
    # ### end Alembic commands ###
